### ISSUE TITLE
Fix Brightness 

### ISSUE THREAD

**Issue by YashAgarwalDev** [hpnightowl/android_device_yu_lettuce#1]
Brightness needs to be adjust more high and set lowest level to 1

**Comment by hpnightowl** [comment]
Hope this will Fix Brightness https://github.com/hpnightowl/android_device_yu_lettuce/commit/72a2b6ea3480ab86bbec44112e17384463ef4a64

**Comment by hpnightowl** [comment]
still there that's why opened sad

**Comment by hpnightowl** [comment]
wew finally fixed
