### ISSUE TITLE
Change Minimum and lowest brightness Values.

### ISSUE THREAD

**Issue by YashAgarwalDev** [hpnightowl/android_device_yu_lettuce#13]
still minimum brightness is too high

**Comment by hpnightowl** [comment]
Again?

**Comment by YashAgarwalDev** [comment]
lol just need to re edit it because , minimum brightness thats called 50% is high like im using 100%

**Comment by hpnightowl** [comment]
ohk will see then you should open the older brightness issue no need to create a new just add comment in that next time :)

**Comment by YashAgarwalDev** [comment]
> ohk will see then you should open the older brightness issue no need to create a new just add comment in that next time :)

ok , dude
