### ISSUE TITLE
Location service Icon is permanently showing

### ISSUE THREAD

**Issue by YashAgarwalDev** [hpnightowl/android_device_yu_lettuce#14]
IDK why its happen may be ROM issue , or something else but location Icon never hides even if i'm not using any app that uses location , like camera , maps etc.

**Comment by hpnightowl** [comment]
strange issue check after restart

**Comment by YashAgarwalDev** [comment]
> strange issue check after restart

same

**Comment by YashAgarwalDev** [comment]
fixed , its a ROM side issue.

**Comment by hpnightowl** [comment]
Great :)
