### ISSUE TITLE
New to fix kernel Random Shutdown on 60%

### ISSUE THREAD

**Issue by YashAgarwalDev** [hpnightowl/android_device_yu_lettuce#2]
Currently shutdown at 60% need more tuning and adjustments

**Comment by YashAgarwalDev** [comment]
Slow Charging issue Very Slow Respond

**Comment by hpnightowl** [comment]
i think lower freq occuring this 60% shutdown issue to removing this commit https://github.com/hpnightowl/android_device_yu_lettuce/commit/1f35fbcaa53f20abf20d061abf2d0b7817ef6bc8
