### ISSUE TITLE
Ambient Display is broken

### ISSUE THREAD

**Issue by YashAgarwalDev** [hpnightowl/android_device_yu_lettuce#3]
Ambient Display is fully broken need to be fixed

**Comment by hpnightowl** [comment]
Fixed @ https://github.com/hpnightowl/android_device_yu_lettuce/commit/a72e4fe14a30aec4be4a92816e9bb21593d8554b https://github.com/hpnightowl/android_device_yu_lettuce/commit/4784d430552886b3c1f952ffa465015ae9a1a6ff
